// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// return10
int return10();
RcppExport SEXP _CompletenessTestData_return10() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(return10());
    return rcpp_result_gen;
END_RCPP
}
// chooseGenomes
std::vector<int> chooseGenomes(std::vector<int> lengthSums, int minContigLength, int seed, int times);
RcppExport SEXP _CompletenessTestData_chooseGenomes(SEXP lengthSumsSEXP, SEXP minContigLengthSEXP, SEXP seedSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type lengthSums(lengthSumsSEXP);
    Rcpp::traits::input_parameter< int >::type minContigLength(minContigLengthSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(chooseGenomes(lengthSums, minContigLength, seed, times));
    return rcpp_result_gen;
END_RCPP
}
// randomSpaces
std::vector<int> randomSpaces(int numSp, int free, int seed);
RcppExport SEXP _CompletenessTestData_randomSpaces(SEXP numSpSEXP, SEXP freeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type numSp(numSpSEXP);
    Rcpp::traits::input_parameter< int >::type free(freeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(randomSpaces(numSp, free, seed));
    return rcpp_result_gen;
END_RCPP
}
// mkContigs
std::vector<std::vector<int> > mkContigs(std::list<std::vector<int> >& lengths, std::vector<int>& lengthSums, std::vector<int>& total, std::vector<int>& partial, int minContigLength, int meanContigLength, int number, std::vector<double>& comp, std::vector<double>& cont, std::vector<std::vector<int> >& names, std::vector<int>& access, int seed, std::string distr);
RcppExport SEXP _CompletenessTestData_mkContigs(SEXP lengthsSEXP, SEXP lengthSumsSEXP, SEXP totalSEXP, SEXP partialSEXP, SEXP minContigLengthSEXP, SEXP meanContigLengthSEXP, SEXP numberSEXP, SEXP compSEXP, SEXP contSEXP, SEXP namesSEXP, SEXP accessSEXP, SEXP seedSEXP, SEXP distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::list<std::vector<int> >& >::type lengths(lengthsSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type lengthSums(lengthSumsSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type total(totalSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type partial(partialSEXP);
    Rcpp::traits::input_parameter< int >::type minContigLength(minContigLengthSEXP);
    Rcpp::traits::input_parameter< int >::type meanContigLength(meanContigLengthSEXP);
    Rcpp::traits::input_parameter< int >::type number(numberSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type comp(compSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type cont(contSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int> >& >::type names(namesSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type access(accessSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type distr(distrSEXP);
    rcpp_result_gen = Rcpp::wrap(mkContigs(lengths, lengthSums, total, partial, minContigLength, meanContigLength, number, comp, cont, names, access, seed, distr));
    return rcpp_result_gen;
END_RCPP
}
// countPifams
List countPifams(std::list<std::list<std::vector<int> > >& pifams, std::list<std::list<std::vector<int> > >& ORFs, std::vector<std::vector<int> >& contigs, std::vector<int>& names, std::vector<int>& total, std::vector<int>& partial);
RcppExport SEXP _CompletenessTestData_countPifams(SEXP pifamsSEXP, SEXP ORFsSEXP, SEXP contigsSEXP, SEXP namesSEXP, SEXP totalSEXP, SEXP partialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::list<std::list<std::vector<int> > >& >::type pifams(pifamsSEXP);
    Rcpp::traits::input_parameter< std::list<std::list<std::vector<int> > >& >::type ORFs(ORFsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int> >& >::type contigs(contigsSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type names(namesSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type total(totalSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type partial(partialSEXP);
    rcpp_result_gen = Rcpp::wrap(countPifams(pifams, ORFs, contigs, names, total, partial));
    return rcpp_result_gen;
END_RCPP
}
// compTestData
List compTestData(std::list<std::list<std::vector<int> > >& pifams, std::list<std::list<std::vector<int> > >& ORFs, std::list<std::vector<int> >& lengths, std::vector<int>& lengthSums, int minContigLength, int meanContigLength, int number, std::vector<double>& comp, std::vector<double>& con, std::vector<std::vector<int> >& names, int seed, std::string distr);
RcppExport SEXP _CompletenessTestData_compTestData(SEXP pifamsSEXP, SEXP ORFsSEXP, SEXP lengthsSEXP, SEXP lengthSumsSEXP, SEXP minContigLengthSEXP, SEXP meanContigLengthSEXP, SEXP numberSEXP, SEXP compSEXP, SEXP conSEXP, SEXP namesSEXP, SEXP seedSEXP, SEXP distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::list<std::list<std::vector<int> > >& >::type pifams(pifamsSEXP);
    Rcpp::traits::input_parameter< std::list<std::list<std::vector<int> > >& >::type ORFs(ORFsSEXP);
    Rcpp::traits::input_parameter< std::list<std::vector<int> >& >::type lengths(lengthsSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type lengthSums(lengthSumsSEXP);
    Rcpp::traits::input_parameter< int >::type minContigLength(minContigLengthSEXP);
    Rcpp::traits::input_parameter< int >::type meanContigLength(meanContigLengthSEXP);
    Rcpp::traits::input_parameter< int >::type number(numberSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type comp(compSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type con(conSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int> >& >::type names(namesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type distr(distrSEXP);
    rcpp_result_gen = Rcpp::wrap(compTestData(pifams, ORFs, lengths, lengthSums, minContigLength, meanContigLength, number, comp, con, names, seed, distr));
    return rcpp_result_gen;
END_RCPP
}
// chooseGenomesCpp
std::vector<int> chooseGenomesCpp(std::vector<int> lengthSums, int minContigLength, int seed, int times);
RcppExport SEXP _CompletenessTestData_chooseGenomesCpp(SEXP lengthSumsSEXP, SEXP minContigLengthSEXP, SEXP seedSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type lengthSums(lengthSumsSEXP);
    Rcpp::traits::input_parameter< int >::type minContigLength(minContigLengthSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(chooseGenomesCpp(lengthSums, minContigLength, seed, times));
    return rcpp_result_gen;
END_RCPP
}
// testDefaultRandomEngine
int testDefaultRandomEngine(int seed);
RcppExport SEXP _CompletenessTestData_testDefaultRandomEngine(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(testDefaultRandomEngine(seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CompletenessTestData_return10", (DL_FUNC) &_CompletenessTestData_return10, 0},
    {"_CompletenessTestData_chooseGenomes", (DL_FUNC) &_CompletenessTestData_chooseGenomes, 4},
    {"_CompletenessTestData_randomSpaces", (DL_FUNC) &_CompletenessTestData_randomSpaces, 3},
    {"_CompletenessTestData_mkContigs", (DL_FUNC) &_CompletenessTestData_mkContigs, 13},
    {"_CompletenessTestData_countPifams", (DL_FUNC) &_CompletenessTestData_countPifams, 6},
    {"_CompletenessTestData_compTestData", (DL_FUNC) &_CompletenessTestData_compTestData, 12},
    {"_CompletenessTestData_chooseGenomesCpp", (DL_FUNC) &_CompletenessTestData_chooseGenomesCpp, 4},
    {"_CompletenessTestData_testDefaultRandomEngine", (DL_FUNC) &_CompletenessTestData_testDefaultRandomEngine, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CompletenessTestData(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
