# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

return10 <- function() {
    .Call('_CompletenessTestData_return10', PACKAGE = 'CompletenessTestData')
}

chooseGenomes <- function(lengthSums, minContigLength, seed = 1L, times = 100L) {
    .Call('_CompletenessTestData_chooseGenomes', PACKAGE = 'CompletenessTestData', lengthSums, minContigLength, seed, times)
}

#' @export
randomSpaces <- function(numSp, free, seed) {
    .Call('_CompletenessTestData_randomSpaces', PACKAGE = 'CompletenessTestData', numSp, free, seed)
}

#' @export
mkContigs <- function(lengths, lengthSums, minContigLength, meanContigLength, number, comp, cont, names, access, seed = 0L, distr = "normal") {
    .Call('_CompletenessTestData_mkContigs', PACKAGE = 'CompletenessTestData', lengths, lengthSums, minContigLength, meanContigLength, number, comp, cont, names, access, seed, distr)
}

#' @export
countPifams <- function(pifams, ORFs, contigs, names) {
    .Call('_CompletenessTestData_countPifams', PACKAGE = 'CompletenessTestData', pifams, ORFs, contigs, names)
}

compTestData <- function(pifams, ORFs, lengths, lengthSums, minContigLength, meanContigLength, number, comp, con, names, seed = 0L, distr = "normal") {
    .Call('_CompletenessTestData_compTestData', PACKAGE = 'CompletenessTestData', pifams, ORFs, lengths, lengthSums, minContigLength, meanContigLength, number, comp, con, names, seed, distr)
}

#' @export
chooseGenomesCpp <- function(lengthSums, minContigLength, seed = 1L, times = 100L) {
    .Call('_CompletenessTestData_chooseGenomesCpp', PACKAGE = 'CompletenessTestData', lengthSums, minContigLength, seed, times)
}

#' @export
testDefaultRandomEngine <- function(seed) {
    .Call('_CompletenessTestData_testDefaultRandomEngine', PACKAGE = 'CompletenessTestData', seed)
}

