# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compTestData <- function(pifams, ORFs, lengths, lengthSums, minContigLength, meanContigLength, number, comp, con, names, seed = 0L, distr = "normal") {
    .Call('_CompletenessTestData_compTestData', PACKAGE = 'CompletenessTestData', pifams, ORFs, lengths, lengthSums, minContigLength, meanContigLength, number, comp, con, names, seed, distr)
}

