# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
randomSpaces <- function(numSp, free, seed) {
    .Call('_CompletenessTestData_randomSpaces', PACKAGE = 'CompletenessTestData', numSp, free, seed)
}

#' @export
mkContigs <- function(lengths, lengthSums, minContigLength, meanContigLength, number, comp, cont, names, access, seed = 0L, distr = "normal") {
    .Call('_CompletenessTestData_mkContigs', PACKAGE = 'CompletenessTestData', lengths, lengthSums, minContigLength, meanContigLength, number, comp, cont, names, access, seed, distr)
}

compTestData <- function(pifams, ORFs, lengths, lengthSums, minContigLength, meanContigLength, number, comp, con, names, seed = 0L, distr = "normal") {
    .Call('_CompletenessTestData_compTestData', PACKAGE = 'CompletenessTestData', pifams, ORFs, lengths, lengthSums, minContigLength, meanContigLength, number, comp, con, names, seed, distr)
}

